### ISSUE TITLE
Modular Missile Guidance Radar guidance mode and launch distance

### ISSUE THREAD

**Issue by SuicidalInsanity** [jrodrigv/BDModularMissileParts#1]
Radar guided MMGs do not track targets; missiles simply follow trajectory they had at time of launch. Switching vessels post launch to missiles to monitor them, the missiles showed no attempts at course correction/fin actuation either pre or post engine cutoff; comparison test with a heatseeker showed it attempting to come about even when ballistic and falling to the ground, 

Additionally: MMGs do not correctly save Max Static Launch Range and Min Static Launch Range
Included on the side of the test vessel is a structural beam with several MMGs. From nose to back, max/min ranges were set to:
 5000/0; 6000/200; 7000/300; 8000/500; 10000/1000; 12000/1500; 20000/2500; 30000/4000.
Loading the vessel in the SPH and checking these values, Max/min ranges changed to:
7500/500;  7500/500; 8750/500; 10000/500; 12500/500 15000/500; 25000/500; 37500/500

Test vessel
[https://github.com/SuicidalInsanity/Misc/releases/tag/0.5](url)

**Comment by jrodrigv** [comment]
Thanks. Can you also attach the KSP.log file generated?

**Comment by SuicidalInsanity** [comment]
[https://github.com/SuicidalInsanity/Misc/releases/download/0.5/output_log.txt](url)

**Comment by jrodrigv** [comment]
Ok! I have reviewed your craft! BTW I really like your missile designs.

I have noticed some pending things in your craft:

1. You forgot to add the first stage of all the missiles. You need add the the active engine action of the SRBs into the Custom1 action group.
2. Also you forgot to add some of the second stages. (Only the boosters of the missile with the jet engine was set)
3. Tip1: I really recommend to increase the Boresight for modular missiles. They are not as stable as the stock BDArmory missiles because they are actually affected by aero forces (BDArmory missiles have everything simulated in code).
3. Tip2: You are better off increasing the detonation radius because modular missiles are not as accurate as stock missiles (due to same reason).

Also I have removed a strange decoupler with 7 or 8 modular missiles devices attached - Not sure why you had added such a strange thing haha but I'm sure it can cause problems.


Finally, please find attached a new version of your craft. It works, I have literally erased  a couple of my planes.


[Aeris 3A Aftermarket_V2.zip](https://github.com/jrodrigv/BDModularMissileParts/files/879675/Aeris.3A.Aftermarket_V2.zip)

**Comment by jrodrigv** [comment]
One more tip:

You need to check the actual "useful" range of your missile  and then adjust the max static launch range accordingly.

**Comment by SuicidalInsanity** [comment]
Thanks for the assist; took a look, and you're correct about the boresights. Increasing them fixed the missile tracking issue. Not sure what was going on with the AGs, missile stages were added to Custom1/2, and the V2 you sent back had no AGs assigned; guess something ate them during transfer.

The strange decoupler with MMGs isn't part of the plane, it was added afterwards solely to showcase the Max/Min Static Launch Range values resetting themselves on craft load issue.

**Comment by jrodrigv** [comment]
BTW do you like this new feature? Are you missing something?

**Comment by SuicidalInsanity** [comment]
Yeah, I'm liking the procedural missiles a lot.  Don't think I'm missing anything, but but one thing I'd suggest would be changing the ProceduralMissileSRB to use ModuleEnginesFX and switching out the engine and smoke FX for something smaller than the 1.25m SRB FX it's currently using.
